/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Account {
  'id' : string,
  'soldeDebit' : Amount,
  'classe' : bigint,
  'libelle' : string,
  'type' : AccountType,
  'numero' : string,
  'soldeCredit' : Amount,
  'compteParent' : [] | [string],
}
export interface AccountBalance {
  'totalCredit' : Amount,
  'estDebiteur' : boolean,
  'solde' : Amount,
  'compte' : Account,
  'totalDebit' : Amount,
}
export type AccountType = { 'Passif' : null } |
  { 'Bilan' : null } |
  { 'Charges' : null } |
  { 'Produits' : null } |
  { 'Actif' : null };
export type Amount = bigint;
export interface BilanData {
  'totalActif' : Amount,
  'exercice' : bigint,
  'passifDetails' : Array<AccountBalance>,
  'estEquilibre' : boolean,
  'actifDetails' : Array<AccountBalance>,
  'totalPassif' : Amount,
}
export interface CompanyInfo {
  'rc' : string,
  'nif' : string,
  'nis' : string,
  'nom' : string,
  'email' : string,
  'exerciceActuel' : bigint,
  'adresse' : string,
  'telephone' : string,
  'activite' : string,
}
export interface CompteResultatsData {
  'totalProduits' : Amount,
  'resultatNet' : Amount,
  'produitsDetails' : Array<AccountBalance>,
  'exercice' : bigint,
  'estBenefice' : boolean,
  'totalCharges' : Amount,
  'chargesDetails' : Array<AccountBalance>,
}
export interface CompteTresorerie {
  'id' : string,
  'actif' : boolean,
  'libelle' : string,
  'compteComptable' : string,
  'type' : TresoType,
  'banque' : [] | [string],
  'solde' : Amount,
  'numeroCompte' : [] | [string],
}
export interface CompteTresorerieInput {
  'libelle' : string,
  'compteComptable' : string,
  'soldeinitial' : Amount,
  'type' : TresoType,
  'banque' : [] | [string],
  'numeroCompte' : [] | [string],
}
export interface EcritureComptable {
  'libelle' : string,
  'credit' : Amount,
  'compte' : string,
  'debit' : Amount,
}
export interface Facture {
  'id' : string,
  'statut' : FactureStatut,
  'date' : Timestamp,
  'totalHT' : Amount,
  'tiersId' : string,
  'type' : FactureType,
  'exercice' : bigint,
  'dateEcheance' : [] | [Timestamp],
  'totalTTC' : Amount,
  'totalTVA' : Amount,
  'notes' : string,
  'numero' : string,
  'lignes' : Array<LigneFacture>,
}
export interface FactureInput {
  'date' : Timestamp,
  'tiersId' : string,
  'type' : FactureType,
  'exercice' : bigint,
  'dateEcheance' : [] | [Timestamp],
  'notes' : string,
  'lignes' : Array<LigneFacture>,
}
export type FactureStatut = { 'Annulee' : null } |
  { 'Validee' : null } |
  { 'Payee' : null } |
  { 'Brouillon' : null };
export type FactureType = { 'Achat' : null } |
  { 'Vente' : null };
export interface FiscalYear {
  'fin' : Timestamp,
  'annee' : bigint,
  'cloture' : boolean,
  'debut' : Timestamp,
}
export interface JournalEntry {
  'id' : string,
  'libelle' : string,
  'date' : Timestamp,
  'valide' : boolean,
  'exercice' : bigint,
  'journalCode' : string,
  'numero' : bigint,
  'ecritures' : Array<EcritureComptable>,
}
export interface JournalEntryInput {
  'libelle' : string,
  'date' : Timestamp,
  'exercice' : bigint,
  'journalCode' : string,
  'ecritures' : Array<EcritureComptable>,
}
export interface LigneFacture {
  'montantHT' : Amount,
  'montantTTC' : Amount,
  'montantTVA' : Amount,
  'designation' : string,
  'tauxTVA' : number,
  'produitId' : [] | [string],
  'quantite' : number,
  'prixUnitaire' : Amount,
}
export interface MouvementStock {
  'id' : string,
  'date' : Timestamp,
  'type' : MouvementType,
  'exercice' : bigint,
  'reference' : string,
  'produitId' : string,
  'notes' : string,
  'quantite' : number,
  'prixUnitaire' : Amount,
}
export interface MouvementStockInput {
  'date' : Timestamp,
  'type' : MouvementType,
  'exercice' : bigint,
  'reference' : string,
  'produitId' : string,
  'notes' : string,
  'quantite' : number,
  'prixUnitaire' : Amount,
}
export interface MouvementTresorerie {
  'id' : string,
  'libelle' : string,
  'date' : Timestamp,
  'type' : MvtType,
  'exercice' : bigint,
  'reference' : string,
  'compteId' : string,
  'montant' : Amount,
}
export interface MouvementTresorerieInput {
  'libelle' : string,
  'date' : Timestamp,
  'type' : MvtType,
  'exercice' : bigint,
  'reference' : string,
  'compteId' : string,
  'montant' : Amount,
}
export type MouvementType = { 'Entree' : null } |
  { 'Sortie' : null } |
  { 'Ajustement' : null };
export type MvtType = { 'Decaissement' : null } |
  { 'Encaissement' : null };
export interface Produit {
  'id' : string,
  'actif' : boolean,
  'code' : string,
  'stockActuel' : number,
  'designation' : string,
  'compteStock' : string,
  'prixAchat' : Amount,
  'prixVente' : Amount,
  'unite' : string,
  'stockMinimum' : number,
}
export interface ProduitInput {
  'code' : string,
  'designation' : string,
  'compteStock' : string,
  'prixAchat' : Amount,
  'prixVente' : Amount,
  'unite' : string,
  'stockMinimum' : number,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export type ResultValue = { 'ok' : string } |
  { 'err' : string };
export type Role = { 'Lecteur' : null } |
  { 'Gestionnaire' : null } |
  { 'Comptable' : null } |
  { 'Admin' : null };
export interface Tiers {
  'id' : string,
  'rc' : string,
  'nif' : string,
  'nis' : string,
  'nom' : string,
  'estClient' : boolean,
  'compteComptable' : string,
  'email' : string,
  'adresse' : string,
  'estFournisseur' : boolean,
  'telephone' : string,
}
export interface TiersInput {
  'rc' : string,
  'nif' : string,
  'nis' : string,
  'nom' : string,
  'estClient' : boolean,
  'compteComptable' : string,
  'email' : string,
  'adresse' : string,
  'estFournisseur' : boolean,
  'telephone' : string,
}
export type Timestamp = bigint;
export type TresoType = { 'Banque' : null } |
  { 'Caisse' : null };
export type UserId = Principal;
export interface UserProfile {
  'nom' : string,
  'actif' : boolean,
  'userId' : UserId,
  'role' : Role,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface ValeurStock {
  'designation' : string,
  'prixMoyenPondere' : Amount,
  'produitId' : string,
  'quantite' : number,
  'valeurTotale' : Amount,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
/**
 * / Hazine — SaaS Comptabilité Algérienne (Conforme SCF - Loi 07-11)
 * / Racine de composition : déclare l'état, importe et inclut les mixins.
 * / Aucune logique métier ici — tout est délégué aux mixins.
 */
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCompte' : ActorMethod<[Account], Result>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cloturerExercice' : ActorMethod<[bigint], Result>,
  'createCompteTresorerie' : ActorMethod<[CompteTresorerieInput], ResultValue>,
  'createExercice' : ActorMethod<[bigint], Result>,
  'createFacture' : ActorMethod<[FactureInput], ResultValue>,
  'createJournalEntry' : ActorMethod<[JournalEntryInput], ResultValue>,
  'createMouvementStock' : ActorMethod<[MouvementStockInput], ResultValue>,
  'createMouvementTresorerie' : ActorMethod<
    [MouvementTresorerieInput],
    ResultValue
  >,
  'createProduit' : ActorMethod<[ProduitInput], ResultValue>,
  'createTiers' : ActorMethod<[TiersInput], ResultValue>,
  'deleteFacture' : ActorMethod<[string], Result>,
  'deleteJournalEntry' : ActorMethod<[string], Result>,
  'getBalance' : ActorMethod<[bigint], Array<AccountBalance>>,
  'getBilan' : ActorMethod<[bigint], BilanData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompanyInfo' : ActorMethod<[], [] | [CompanyInfo]>,
  'getCompteResultats' : ActorMethod<[bigint], CompteResultatsData>,
  'getComptes' : ActorMethod<[], Array<Account>>,
  'getComptesParClasse' : ActorMethod<[bigint], Array<Account>>,
  'getComptesTresorerie' : ActorMethod<[], Array<CompteTresorerie>>,
  'getDashboardStats' : ActorMethod<
    [bigint],
    {
      'totalDettes' : Amount,
      'resultatNet' : Amount,
      'totalCreances' : Amount,
      'nombreFacturesEnAttente' : bigint,
      'alertesStock' : bigint,
      'chiffreAffaires' : Amount,
      'soldeTresorerie' : Amount,
    }
  >,
  'getExercices' : ActorMethod<[], Array<FiscalYear>>,
  'getFacture' : ActorMethod<[string], [] | [Facture]>,
  'getFactures' : ActorMethod<
    [FactureType, bigint, bigint],
    { 'total' : bigint, 'factures' : Array<Facture> }
  >,
  'getGrandLivre' : ActorMethod<[string, bigint], Array<JournalEntry>>,
  'getJournalEntries' : ActorMethod<
    [bigint, bigint],
    { 'total' : bigint, 'entries' : Array<JournalEntry> }
  >,
  'getJournalEntry' : ActorMethod<[string], [] | [JournalEntry]>,
  'getMouvementsStock' : ActorMethod<
    [[] | [string], bigint, bigint],
    { 'mouvements' : Array<MouvementStock>, 'total' : bigint }
  >,
  'getMouvementsTresorerie' : ActorMethod<
    [[] | [string], bigint, bigint],
    { 'mouvements' : Array<MouvementTresorerie>, 'total' : bigint }
  >,
  'getProduit' : ActorMethod<[string], [] | [Produit]>,
  'getProduits' : ActorMethod<[], Array<Produit>>,
  'getProduitsEnRuptureOuAlerte' : ActorMethod<[], Array<Produit>>,
  'getSoldeTresorerie' : ActorMethod<[], Amount>,
  'getTiers' : ActorMethod<[], Array<Tiers>>,
  'getTiersById' : ActorMethod<[string], [] | [Tiers]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsers' : ActorMethod<[], Array<UserProfile>>,
  'getValeurStock' : ActorMethod<[], Array<ValeurStock>>,
  'initData' : ActorMethod<[], undefined>,
  'initTresorerie' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCompanyInfo' : ActorMethod<[CompanyInfo], Result>,
  'updateCompte' : ActorMethod<[string, Account], Result>,
  'updateProduit' : ActorMethod<[string, ProduitInput], Result>,
  'updateTiers' : ActorMethod<[string, TiersInput], Result>,
  'updateUserRole' : ActorMethod<[UserId, Role], Result>,
  'validateFacture' : ActorMethod<[string], Result>,
  'validateJournalEntry' : ActorMethod<[string], Result>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];