/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Amount = IDL.Nat;
export const AccountType = IDL.Variant({
  'Passif' : IDL.Null,
  'Bilan' : IDL.Null,
  'Charges' : IDL.Null,
  'Produits' : IDL.Null,
  'Actif' : IDL.Null,
});
export const Account = IDL.Record({
  'id' : IDL.Text,
  'soldeDebit' : Amount,
  'classe' : IDL.Nat,
  'libelle' : IDL.Text,
  'type' : AccountType,
  'numero' : IDL.Text,
  'soldeCredit' : Amount,
  'compteParent' : IDL.Opt(IDL.Text),
});
export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TresoType = IDL.Variant({
  'Banque' : IDL.Null,
  'Caisse' : IDL.Null,
});
export const CompteTresorerieInput = IDL.Record({
  'libelle' : IDL.Text,
  'compteComptable' : IDL.Text,
  'soldeinitial' : Amount,
  'type' : TresoType,
  'banque' : IDL.Opt(IDL.Text),
  'numeroCompte' : IDL.Opt(IDL.Text),
});
export const ResultValue = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
export const Timestamp = IDL.Int;
export const FactureType = IDL.Variant({
  'Achat' : IDL.Null,
  'Vente' : IDL.Null,
});
export const LigneFacture = IDL.Record({
  'montantHT' : Amount,
  'montantTTC' : Amount,
  'montantTVA' : Amount,
  'designation' : IDL.Text,
  'tauxTVA' : IDL.Float64,
  'produitId' : IDL.Opt(IDL.Text),
  'quantite' : IDL.Float64,
  'prixUnitaire' : Amount,
});
export const FactureInput = IDL.Record({
  'date' : Timestamp,
  'tiersId' : IDL.Text,
  'type' : FactureType,
  'exercice' : IDL.Nat,
  'dateEcheance' : IDL.Opt(Timestamp),
  'notes' : IDL.Text,
  'lignes' : IDL.Vec(LigneFacture),
});
export const EcritureComptable = IDL.Record({
  'libelle' : IDL.Text,
  'credit' : Amount,
  'compte' : IDL.Text,
  'debit' : Amount,
});
export const JournalEntryInput = IDL.Record({
  'libelle' : IDL.Text,
  'date' : Timestamp,
  'exercice' : IDL.Nat,
  'journalCode' : IDL.Text,
  'ecritures' : IDL.Vec(EcritureComptable),
});
export const MouvementType = IDL.Variant({
  'Entree' : IDL.Null,
  'Sortie' : IDL.Null,
  'Ajustement' : IDL.Null,
});
export const MouvementStockInput = IDL.Record({
  'date' : Timestamp,
  'type' : MouvementType,
  'exercice' : IDL.Nat,
  'reference' : IDL.Text,
  'produitId' : IDL.Text,
  'notes' : IDL.Text,
  'quantite' : IDL.Float64,
  'prixUnitaire' : Amount,
});
export const MvtType = IDL.Variant({
  'Decaissement' : IDL.Null,
  'Encaissement' : IDL.Null,
});
export const MouvementTresorerieInput = IDL.Record({
  'libelle' : IDL.Text,
  'date' : Timestamp,
  'type' : MvtType,
  'exercice' : IDL.Nat,
  'reference' : IDL.Text,
  'compteId' : IDL.Text,
  'montant' : Amount,
});
export const ProduitInput = IDL.Record({
  'code' : IDL.Text,
  'designation' : IDL.Text,
  'compteStock' : IDL.Text,
  'prixAchat' : Amount,
  'prixVente' : Amount,
  'unite' : IDL.Text,
  'stockMinimum' : IDL.Float64,
});
export const TiersInput = IDL.Record({
  'rc' : IDL.Text,
  'nif' : IDL.Text,
  'nis' : IDL.Text,
  'nom' : IDL.Text,
  'estClient' : IDL.Bool,
  'compteComptable' : IDL.Text,
  'email' : IDL.Text,
  'adresse' : IDL.Text,
  'estFournisseur' : IDL.Bool,
  'telephone' : IDL.Text,
});
export const AccountBalance = IDL.Record({
  'totalCredit' : Amount,
  'estDebiteur' : IDL.Bool,
  'solde' : Amount,
  'compte' : Account,
  'totalDebit' : Amount,
});
export const BilanData = IDL.Record({
  'totalActif' : Amount,
  'exercice' : IDL.Nat,
  'passifDetails' : IDL.Vec(AccountBalance),
  'estEquilibre' : IDL.Bool,
  'actifDetails' : IDL.Vec(AccountBalance),
  'totalPassif' : Amount,
});
export const UserId = IDL.Principal;
export const Role = IDL.Variant({
  'Lecteur' : IDL.Null,
  'Gestionnaire' : IDL.Null,
  'Comptable' : IDL.Null,
  'Admin' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'nom' : IDL.Text,
  'actif' : IDL.Bool,
  'userId' : UserId,
  'role' : Role,
  'email' : IDL.Text,
});
export const CompanyInfo = IDL.Record({
  'rc' : IDL.Text,
  'nif' : IDL.Text,
  'nis' : IDL.Text,
  'nom' : IDL.Text,
  'email' : IDL.Text,
  'exerciceActuel' : IDL.Nat,
  'adresse' : IDL.Text,
  'telephone' : IDL.Text,
  'activite' : IDL.Text,
});
export const CompteResultatsData = IDL.Record({
  'totalProduits' : Amount,
  'resultatNet' : Amount,
  'produitsDetails' : IDL.Vec(AccountBalance),
  'exercice' : IDL.Nat,
  'estBenefice' : IDL.Bool,
  'totalCharges' : Amount,
  'chargesDetails' : IDL.Vec(AccountBalance),
});
export const CompteTresorerie = IDL.Record({
  'id' : IDL.Text,
  'actif' : IDL.Bool,
  'libelle' : IDL.Text,
  'compteComptable' : IDL.Text,
  'type' : TresoType,
  'banque' : IDL.Opt(IDL.Text),
  'solde' : Amount,
  'numeroCompte' : IDL.Opt(IDL.Text),
});
export const FiscalYear = IDL.Record({
  'fin' : Timestamp,
  'annee' : IDL.Nat,
  'cloture' : IDL.Bool,
  'debut' : Timestamp,
});
export const FactureStatut = IDL.Variant({
  'Annulee' : IDL.Null,
  'Validee' : IDL.Null,
  'Payee' : IDL.Null,
  'Brouillon' : IDL.Null,
});
export const Facture = IDL.Record({
  'id' : IDL.Text,
  'statut' : FactureStatut,
  'date' : Timestamp,
  'totalHT' : Amount,
  'tiersId' : IDL.Text,
  'type' : FactureType,
  'exercice' : IDL.Nat,
  'dateEcheance' : IDL.Opt(Timestamp),
  'totalTTC' : Amount,
  'totalTVA' : Amount,
  'notes' : IDL.Text,
  'numero' : IDL.Text,
  'lignes' : IDL.Vec(LigneFacture),
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'libelle' : IDL.Text,
  'date' : Timestamp,
  'valide' : IDL.Bool,
  'exercice' : IDL.Nat,
  'journalCode' : IDL.Text,
  'numero' : IDL.Nat,
  'ecritures' : IDL.Vec(EcritureComptable),
});
export const MouvementStock = IDL.Record({
  'id' : IDL.Text,
  'date' : Timestamp,
  'type' : MouvementType,
  'exercice' : IDL.Nat,
  'reference' : IDL.Text,
  'produitId' : IDL.Text,
  'notes' : IDL.Text,
  'quantite' : IDL.Float64,
  'prixUnitaire' : Amount,
});
export const MouvementTresorerie = IDL.Record({
  'id' : IDL.Text,
  'libelle' : IDL.Text,
  'date' : Timestamp,
  'type' : MvtType,
  'exercice' : IDL.Nat,
  'reference' : IDL.Text,
  'compteId' : IDL.Text,
  'montant' : Amount,
});
export const Produit = IDL.Record({
  'id' : IDL.Text,
  'actif' : IDL.Bool,
  'code' : IDL.Text,
  'stockActuel' : IDL.Float64,
  'designation' : IDL.Text,
  'compteStock' : IDL.Text,
  'prixAchat' : Amount,
  'prixVente' : Amount,
  'unite' : IDL.Text,
  'stockMinimum' : IDL.Float64,
});
export const Tiers = IDL.Record({
  'id' : IDL.Text,
  'rc' : IDL.Text,
  'nif' : IDL.Text,
  'nis' : IDL.Text,
  'nom' : IDL.Text,
  'estClient' : IDL.Bool,
  'compteComptable' : IDL.Text,
  'email' : IDL.Text,
  'adresse' : IDL.Text,
  'estFournisseur' : IDL.Bool,
  'telephone' : IDL.Text,
});
export const ValeurStock = IDL.Record({
  'designation' : IDL.Text,
  'prixMoyenPondere' : Amount,
  'produitId' : IDL.Text,
  'quantite' : IDL.Float64,
  'valeurTotale' : Amount,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCompte' : IDL.Func([Account], [Result], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cloturerExercice' : IDL.Func([IDL.Nat], [Result], []),
  'createCompteTresorerie' : IDL.Func(
      [CompteTresorerieInput],
      [ResultValue],
      [],
    ),
  'createExercice' : IDL.Func([IDL.Nat], [Result], []),
  'createFacture' : IDL.Func([FactureInput], [ResultValue], []),
  'createJournalEntry' : IDL.Func([JournalEntryInput], [ResultValue], []),
  'createMouvementStock' : IDL.Func([MouvementStockInput], [ResultValue], []),
  'createMouvementTresorerie' : IDL.Func(
      [MouvementTresorerieInput],
      [ResultValue],
      [],
    ),
  'createProduit' : IDL.Func([ProduitInput], [ResultValue], []),
  'createTiers' : IDL.Func([TiersInput], [ResultValue], []),
  'deleteFacture' : IDL.Func([IDL.Text], [Result], []),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [Result], []),
  'getBalance' : IDL.Func([IDL.Nat], [IDL.Vec(AccountBalance)], ['query']),
  'getBilan' : IDL.Func([IDL.Nat], [BilanData], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompanyInfo' : IDL.Func([], [IDL.Opt(CompanyInfo)], ['query']),
  'getCompteResultats' : IDL.Func([IDL.Nat], [CompteResultatsData], ['query']),
  'getComptes' : IDL.Func([], [IDL.Vec(Account)], ['query']),
  'getComptesParClasse' : IDL.Func([IDL.Nat], [IDL.Vec(Account)], ['query']),
  'getComptesTresorerie' : IDL.Func([], [IDL.Vec(CompteTresorerie)], ['query']),
  'getDashboardStats' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'totalDettes' : Amount,
          'resultatNet' : Amount,
          'totalCreances' : Amount,
          'nombreFacturesEnAttente' : IDL.Nat,
          'alertesStock' : IDL.Nat,
          'chiffreAffaires' : Amount,
          'soldeTresorerie' : Amount,
        }),
      ],
      ['query'],
    ),
  'getExercices' : IDL.Func([], [IDL.Vec(FiscalYear)], ['query']),
  'getFacture' : IDL.Func([IDL.Text], [IDL.Opt(Facture)], ['query']),
  'getFactures' : IDL.Func(
      [FactureType, IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'factures' : IDL.Vec(Facture) })],
      ['query'],
    ),
  'getGrandLivre' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'getJournalEntries' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(JournalEntry) })],
      ['query'],
    ),
  'getJournalEntry' : IDL.Func([IDL.Text], [IDL.Opt(JournalEntry)], ['query']),
  'getMouvementsStock' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'mouvements' : IDL.Vec(MouvementStock),
          'total' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMouvementsTresorerie' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'mouvements' : IDL.Vec(MouvementTresorerie),
          'total' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getProduit' : IDL.Func([IDL.Text], [IDL.Opt(Produit)], ['query']),
  'getProduits' : IDL.Func([], [IDL.Vec(Produit)], ['query']),
  'getProduitsEnRuptureOuAlerte' : IDL.Func([], [IDL.Vec(Produit)], ['query']),
  'getSoldeTresorerie' : IDL.Func([], [Amount], ['query']),
  'getTiers' : IDL.Func([], [IDL.Vec(Tiers)], ['query']),
  'getTiersById' : IDL.Func([IDL.Text], [IDL.Opt(Tiers)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getValeurStock' : IDL.Func([], [IDL.Vec(ValeurStock)], ['query']),
  'initData' : IDL.Func([], [], []),
  'initTresorerie' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCompanyInfo' : IDL.Func([CompanyInfo], [Result], []),
  'updateCompte' : IDL.Func([IDL.Text, Account], [Result], []),
  'updateProduit' : IDL.Func([IDL.Text, ProduitInput], [Result], []),
  'updateTiers' : IDL.Func([IDL.Text, TiersInput], [Result], []),
  'updateUserRole' : IDL.Func([UserId, Role], [Result], []),
  'validateFacture' : IDL.Func([IDL.Text], [Result], []),
  'validateJournalEntry' : IDL.Func([IDL.Text], [Result], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Amount = IDL.Nat;
  const AccountType = IDL.Variant({
    'Passif' : IDL.Null,
    'Bilan' : IDL.Null,
    'Charges' : IDL.Null,
    'Produits' : IDL.Null,
    'Actif' : IDL.Null,
  });
  const Account = IDL.Record({
    'id' : IDL.Text,
    'soldeDebit' : Amount,
    'classe' : IDL.Nat,
    'libelle' : IDL.Text,
    'type' : AccountType,
    'numero' : IDL.Text,
    'soldeCredit' : Amount,
    'compteParent' : IDL.Opt(IDL.Text),
  });
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TresoType = IDL.Variant({ 'Banque' : IDL.Null, 'Caisse' : IDL.Null });
  const CompteTresorerieInput = IDL.Record({
    'libelle' : IDL.Text,
    'compteComptable' : IDL.Text,
    'soldeinitial' : Amount,
    'type' : TresoType,
    'banque' : IDL.Opt(IDL.Text),
    'numeroCompte' : IDL.Opt(IDL.Text),
  });
  const ResultValue = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  const Timestamp = IDL.Int;
  const FactureType = IDL.Variant({ 'Achat' : IDL.Null, 'Vente' : IDL.Null });
  const LigneFacture = IDL.Record({
    'montantHT' : Amount,
    'montantTTC' : Amount,
    'montantTVA' : Amount,
    'designation' : IDL.Text,
    'tauxTVA' : IDL.Float64,
    'produitId' : IDL.Opt(IDL.Text),
    'quantite' : IDL.Float64,
    'prixUnitaire' : Amount,
  });
  const FactureInput = IDL.Record({
    'date' : Timestamp,
    'tiersId' : IDL.Text,
    'type' : FactureType,
    'exercice' : IDL.Nat,
    'dateEcheance' : IDL.Opt(Timestamp),
    'notes' : IDL.Text,
    'lignes' : IDL.Vec(LigneFacture),
  });
  const EcritureComptable = IDL.Record({
    'libelle' : IDL.Text,
    'credit' : Amount,
    'compte' : IDL.Text,
    'debit' : Amount,
  });
  const JournalEntryInput = IDL.Record({
    'libelle' : IDL.Text,
    'date' : Timestamp,
    'exercice' : IDL.Nat,
    'journalCode' : IDL.Text,
    'ecritures' : IDL.Vec(EcritureComptable),
  });
  const MouvementType = IDL.Variant({
    'Entree' : IDL.Null,
    'Sortie' : IDL.Null,
    'Ajustement' : IDL.Null,
  });
  const MouvementStockInput = IDL.Record({
    'date' : Timestamp,
    'type' : MouvementType,
    'exercice' : IDL.Nat,
    'reference' : IDL.Text,
    'produitId' : IDL.Text,
    'notes' : IDL.Text,
    'quantite' : IDL.Float64,
    'prixUnitaire' : Amount,
  });
  const MvtType = IDL.Variant({
    'Decaissement' : IDL.Null,
    'Encaissement' : IDL.Null,
  });
  const MouvementTresorerieInput = IDL.Record({
    'libelle' : IDL.Text,
    'date' : Timestamp,
    'type' : MvtType,
    'exercice' : IDL.Nat,
    'reference' : IDL.Text,
    'compteId' : IDL.Text,
    'montant' : Amount,
  });
  const ProduitInput = IDL.Record({
    'code' : IDL.Text,
    'designation' : IDL.Text,
    'compteStock' : IDL.Text,
    'prixAchat' : Amount,
    'prixVente' : Amount,
    'unite' : IDL.Text,
    'stockMinimum' : IDL.Float64,
  });
  const TiersInput = IDL.Record({
    'rc' : IDL.Text,
    'nif' : IDL.Text,
    'nis' : IDL.Text,
    'nom' : IDL.Text,
    'estClient' : IDL.Bool,
    'compteComptable' : IDL.Text,
    'email' : IDL.Text,
    'adresse' : IDL.Text,
    'estFournisseur' : IDL.Bool,
    'telephone' : IDL.Text,
  });
  const AccountBalance = IDL.Record({
    'totalCredit' : Amount,
    'estDebiteur' : IDL.Bool,
    'solde' : Amount,
    'compte' : Account,
    'totalDebit' : Amount,
  });
  const BilanData = IDL.Record({
    'totalActif' : Amount,
    'exercice' : IDL.Nat,
    'passifDetails' : IDL.Vec(AccountBalance),
    'estEquilibre' : IDL.Bool,
    'actifDetails' : IDL.Vec(AccountBalance),
    'totalPassif' : Amount,
  });
  const UserId = IDL.Principal;
  const Role = IDL.Variant({
    'Lecteur' : IDL.Null,
    'Gestionnaire' : IDL.Null,
    'Comptable' : IDL.Null,
    'Admin' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'nom' : IDL.Text,
    'actif' : IDL.Bool,
    'userId' : UserId,
    'role' : Role,
    'email' : IDL.Text,
  });
  const CompanyInfo = IDL.Record({
    'rc' : IDL.Text,
    'nif' : IDL.Text,
    'nis' : IDL.Text,
    'nom' : IDL.Text,
    'email' : IDL.Text,
    'exerciceActuel' : IDL.Nat,
    'adresse' : IDL.Text,
    'telephone' : IDL.Text,
    'activite' : IDL.Text,
  });
  const CompteResultatsData = IDL.Record({
    'totalProduits' : Amount,
    'resultatNet' : Amount,
    'produitsDetails' : IDL.Vec(AccountBalance),
    'exercice' : IDL.Nat,
    'estBenefice' : IDL.Bool,
    'totalCharges' : Amount,
    'chargesDetails' : IDL.Vec(AccountBalance),
  });
  const CompteTresorerie = IDL.Record({
    'id' : IDL.Text,
    'actif' : IDL.Bool,
    'libelle' : IDL.Text,
    'compteComptable' : IDL.Text,
    'type' : TresoType,
    'banque' : IDL.Opt(IDL.Text),
    'solde' : Amount,
    'numeroCompte' : IDL.Opt(IDL.Text),
  });
  const FiscalYear = IDL.Record({
    'fin' : Timestamp,
    'annee' : IDL.Nat,
    'cloture' : IDL.Bool,
    'debut' : Timestamp,
  });
  const FactureStatut = IDL.Variant({
    'Annulee' : IDL.Null,
    'Validee' : IDL.Null,
    'Payee' : IDL.Null,
    'Brouillon' : IDL.Null,
  });
  const Facture = IDL.Record({
    'id' : IDL.Text,
    'statut' : FactureStatut,
    'date' : Timestamp,
    'totalHT' : Amount,
    'tiersId' : IDL.Text,
    'type' : FactureType,
    'exercice' : IDL.Nat,
    'dateEcheance' : IDL.Opt(Timestamp),
    'totalTTC' : Amount,
    'totalTVA' : Amount,
    'notes' : IDL.Text,
    'numero' : IDL.Text,
    'lignes' : IDL.Vec(LigneFacture),
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'libelle' : IDL.Text,
    'date' : Timestamp,
    'valide' : IDL.Bool,
    'exercice' : IDL.Nat,
    'journalCode' : IDL.Text,
    'numero' : IDL.Nat,
    'ecritures' : IDL.Vec(EcritureComptable),
  });
  const MouvementStock = IDL.Record({
    'id' : IDL.Text,
    'date' : Timestamp,
    'type' : MouvementType,
    'exercice' : IDL.Nat,
    'reference' : IDL.Text,
    'produitId' : IDL.Text,
    'notes' : IDL.Text,
    'quantite' : IDL.Float64,
    'prixUnitaire' : Amount,
  });
  const MouvementTresorerie = IDL.Record({
    'id' : IDL.Text,
    'libelle' : IDL.Text,
    'date' : Timestamp,
    'type' : MvtType,
    'exercice' : IDL.Nat,
    'reference' : IDL.Text,
    'compteId' : IDL.Text,
    'montant' : Amount,
  });
  const Produit = IDL.Record({
    'id' : IDL.Text,
    'actif' : IDL.Bool,
    'code' : IDL.Text,
    'stockActuel' : IDL.Float64,
    'designation' : IDL.Text,
    'compteStock' : IDL.Text,
    'prixAchat' : Amount,
    'prixVente' : Amount,
    'unite' : IDL.Text,
    'stockMinimum' : IDL.Float64,
  });
  const Tiers = IDL.Record({
    'id' : IDL.Text,
    'rc' : IDL.Text,
    'nif' : IDL.Text,
    'nis' : IDL.Text,
    'nom' : IDL.Text,
    'estClient' : IDL.Bool,
    'compteComptable' : IDL.Text,
    'email' : IDL.Text,
    'adresse' : IDL.Text,
    'estFournisseur' : IDL.Bool,
    'telephone' : IDL.Text,
  });
  const ValeurStock = IDL.Record({
    'designation' : IDL.Text,
    'prixMoyenPondere' : Amount,
    'produitId' : IDL.Text,
    'quantite' : IDL.Float64,
    'valeurTotale' : Amount,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCompte' : IDL.Func([Account], [Result], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cloturerExercice' : IDL.Func([IDL.Nat], [Result], []),
    'createCompteTresorerie' : IDL.Func(
        [CompteTresorerieInput],
        [ResultValue],
        [],
      ),
    'createExercice' : IDL.Func([IDL.Nat], [Result], []),
    'createFacture' : IDL.Func([FactureInput], [ResultValue], []),
    'createJournalEntry' : IDL.Func([JournalEntryInput], [ResultValue], []),
    'createMouvementStock' : IDL.Func([MouvementStockInput], [ResultValue], []),
    'createMouvementTresorerie' : IDL.Func(
        [MouvementTresorerieInput],
        [ResultValue],
        [],
      ),
    'createProduit' : IDL.Func([ProduitInput], [ResultValue], []),
    'createTiers' : IDL.Func([TiersInput], [ResultValue], []),
    'deleteFacture' : IDL.Func([IDL.Text], [Result], []),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [Result], []),
    'getBalance' : IDL.Func([IDL.Nat], [IDL.Vec(AccountBalance)], ['query']),
    'getBilan' : IDL.Func([IDL.Nat], [BilanData], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompanyInfo' : IDL.Func([], [IDL.Opt(CompanyInfo)], ['query']),
    'getCompteResultats' : IDL.Func(
        [IDL.Nat],
        [CompteResultatsData],
        ['query'],
      ),
    'getComptes' : IDL.Func([], [IDL.Vec(Account)], ['query']),
    'getComptesParClasse' : IDL.Func([IDL.Nat], [IDL.Vec(Account)], ['query']),
    'getComptesTresorerie' : IDL.Func(
        [],
        [IDL.Vec(CompteTresorerie)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'totalDettes' : Amount,
            'resultatNet' : Amount,
            'totalCreances' : Amount,
            'nombreFacturesEnAttente' : IDL.Nat,
            'alertesStock' : IDL.Nat,
            'chiffreAffaires' : Amount,
            'soldeTresorerie' : Amount,
          }),
        ],
        ['query'],
      ),
    'getExercices' : IDL.Func([], [IDL.Vec(FiscalYear)], ['query']),
    'getFacture' : IDL.Func([IDL.Text], [IDL.Opt(Facture)], ['query']),
    'getFactures' : IDL.Func(
        [FactureType, IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'factures' : IDL.Vec(Facture) })],
        ['query'],
      ),
    'getGrandLivre' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'getJournalEntries' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Record({ 'total' : IDL.Nat, 'entries' : IDL.Vec(JournalEntry) })],
        ['query'],
      ),
    'getJournalEntry' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(JournalEntry)],
        ['query'],
      ),
    'getMouvementsStock' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'mouvements' : IDL.Vec(MouvementStock),
            'total' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMouvementsTresorerie' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'mouvements' : IDL.Vec(MouvementTresorerie),
            'total' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getProduit' : IDL.Func([IDL.Text], [IDL.Opt(Produit)], ['query']),
    'getProduits' : IDL.Func([], [IDL.Vec(Produit)], ['query']),
    'getProduitsEnRuptureOuAlerte' : IDL.Func(
        [],
        [IDL.Vec(Produit)],
        ['query'],
      ),
    'getSoldeTresorerie' : IDL.Func([], [Amount], ['query']),
    'getTiers' : IDL.Func([], [IDL.Vec(Tiers)], ['query']),
    'getTiersById' : IDL.Func([IDL.Text], [IDL.Opt(Tiers)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getValeurStock' : IDL.Func([], [IDL.Vec(ValeurStock)], ['query']),
    'initData' : IDL.Func([], [], []),
    'initTresorerie' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCompanyInfo' : IDL.Func([CompanyInfo], [Result], []),
    'updateCompte' : IDL.Func([IDL.Text, Account], [Result], []),
    'updateProduit' : IDL.Func([IDL.Text, ProduitInput], [Result], []),
    'updateTiers' : IDL.Func([IDL.Text, TiersInput], [Result], []),
    'updateUserRole' : IDL.Func([UserId, Role], [Result], []),
    'validateFacture' : IDL.Func([IDL.Text], [Result], []),
    'validateJournalEntry' : IDL.Func([IDL.Text], [Result], []),
  });
};

export const init = ({ IDL }) => { return []; };