/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface CompteTresorerie {
    id: string;
    actif: boolean;
    libelle: string;
    compteComptable: string;
    type: TresoType;
    banque?: string;
    solde: Amount;
    numeroCompte?: string;
}
export interface FactureInput {
    date: Timestamp;
    tiersId: string;
    type: FactureType;
    exercice: bigint;
    dateEcheance?: Timestamp;
    notes: string;
    lignes: Array<LigneFacture>;
}
export type Timestamp = bigint;
export interface Produit {
    id: string;
    actif: boolean;
    code: string;
    stockActuel: number;
    designation: string;
    compteStock: string;
    prixAchat: Amount;
    prixVente: Amount;
    unite: string;
    stockMinimum: number;
}
export interface MouvementTresorerie {
    id: string;
    libelle: string;
    date: Timestamp;
    type: MvtType;
    exercice: bigint;
    reference: string;
    compteId: string;
    montant: Amount;
}
export interface MouvementStockInput {
    date: Timestamp;
    type: MouvementType;
    exercice: bigint;
    reference: string;
    produitId: string;
    notes: string;
    quantite: number;
    prixUnitaire: Amount;
}
export interface LigneFacture {
    montantHT: Amount;
    montantTTC: Amount;
    montantTVA: Amount;
    designation: string;
    tauxTVA: number;
    produitId?: string;
    quantite: number;
    prixUnitaire: Amount;
}
export interface Account {
    id: string;
    soldeDebit: Amount;
    classe: bigint;
    libelle: string;
    type: AccountType;
    numero: string;
    soldeCredit: Amount;
    compteParent?: string;
}
export interface Facture {
    id: string;
    statut: FactureStatut;
    date: Timestamp;
    totalHT: Amount;
    tiersId: string;
    type: FactureType;
    exercice: bigint;
    dateEcheance?: Timestamp;
    totalTTC: Amount;
    totalTVA: Amount;
    notes: string;
    numero: string;
    lignes: Array<LigneFacture>;
}
export interface MouvementStock {
    id: string;
    date: Timestamp;
    type: MouvementType;
    exercice: bigint;
    reference: string;
    produitId: string;
    notes: string;
    quantite: number;
    prixUnitaire: Amount;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface BilanData {
    totalActif: Amount;
    exercice: bigint;
    passifDetails: Array<AccountBalance>;
    estEquilibre: boolean;
    actifDetails: Array<AccountBalance>;
    totalPassif: Amount;
}
export interface CompteResultatsData {
    totalProduits: Amount;
    resultatNet: Amount;
    produitsDetails: Array<AccountBalance>;
    exercice: bigint;
    estBenefice: boolean;
    totalCharges: Amount;
    chargesDetails: Array<AccountBalance>;
}
export interface EcritureComptable {
    libelle: string;
    credit: Amount;
    compte: string;
    debit: Amount;
}
export interface TiersInput {
    rc: string;
    nif: string;
    nis: string;
    nom: string;
    estClient: boolean;
    compteComptable: string;
    email: string;
    adresse: string;
    estFournisseur: boolean;
    telephone: string;
}
export interface AccountBalance {
    totalCredit: Amount;
    estDebiteur: boolean;
    solde: Amount;
    compte: Account;
    totalDebit: Amount;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface CompanyInfo {
    rc: string;
    nif: string;
    nis: string;
    nom: string;
    email: string;
    exerciceActuel: bigint;
    adresse: string;
    telephone: string;
    activite: string;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Tiers {
    id: string;
    rc: string;
    nif: string;
    nis: string;
    nom: string;
    estClient: boolean;
    compteComptable: string;
    email: string;
    adresse: string;
    estFournisseur: boolean;
    telephone: string;
}
export type Amount = bigint;
export type ResultValue = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export interface ProduitInput {
    code: string;
    designation: string;
    compteStock: string;
    prixAchat: Amount;
    prixVente: Amount;
    unite: string;
    stockMinimum: number;
}
export interface MouvementTresorerieInput {
    libelle: string;
    date: Timestamp;
    type: MvtType;
    exercice: bigint;
    reference: string;
    compteId: string;
    montant: Amount;
}
export type UserId = Principal;
export interface FiscalYear {
    fin: Timestamp;
    annee: bigint;
    cloture: boolean;
    debut: Timestamp;
}
export type Result = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export interface JournalEntry {
    id: string;
    libelle: string;
    date: Timestamp;
    valide: boolean;
    exercice: bigint;
    journalCode: string;
    numero: bigint;
    ecritures: Array<EcritureComptable>;
}
export interface CompteTresorerieInput {
    libelle: string;
    compteComptable: string;
    soldeinitial: Amount;
    type: TresoType;
    banque?: string;
    numeroCompte?: string;
}
export interface JournalEntryInput {
    libelle: string;
    date: Timestamp;
    exercice: bigint;
    journalCode: string;
    ecritures: Array<EcritureComptable>;
}
export interface ValeurStock {
    designation: string;
    prixMoyenPondere: Amount;
    produitId: string;
    quantite: number;
    valeurTotale: Amount;
}
export interface UserProfile {
    nom: string;
    actif: boolean;
    userId: UserId;
    role: Role;
    email: string;
}
export enum AccountType {
    Passif = "Passif",
    Bilan = "Bilan",
    Charges = "Charges",
    Produits = "Produits",
    Actif = "Actif"
}
export enum FactureStatut {
    Annulee = "Annulee",
    Validee = "Validee",
    Payee = "Payee",
    Brouillon = "Brouillon"
}
export enum FactureType {
    Achat = "Achat",
    Vente = "Vente"
}
export enum MouvementType {
    Entree = "Entree",
    Sortie = "Sortie",
    Ajustement = "Ajustement"
}
export enum MvtType {
    Decaissement = "Decaissement",
    Encaissement = "Encaissement"
}
export enum Role {
    Lecteur = "Lecteur",
    Gestionnaire = "Gestionnaire",
    Comptable = "Comptable",
    Admin = "Admin"
}
export enum TresoType {
    Banque = "Banque",
    Caisse = "Caisse"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
/**
 * / Hazine — SaaS Comptabilité Algérienne (Conforme SCF - Loi 07-11)
 * / Racine de composition : déclare l'état, importe et inclut les mixins.
 * / Aucune logique métier ici — tout est délégué aux mixins.
 */
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCompte(compte: Account): Promise<Result>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cloturerExercice(annee: bigint): Promise<Result>;
    createCompteTresorerie(compte: CompteTresorerieInput): Promise<ResultValue>;
    createExercice(annee: bigint): Promise<Result>;
    createFacture(facture: FactureInput): Promise<ResultValue>;
    createJournalEntry(entry: JournalEntryInput): Promise<ResultValue>;
    createMouvementStock(mvt: MouvementStockInput): Promise<ResultValue>;
    createMouvementTresorerie(mvt: MouvementTresorerieInput): Promise<ResultValue>;
    createProduit(produit: ProduitInput): Promise<ResultValue>;
    createTiers(input: TiersInput): Promise<ResultValue>;
    deleteFacture(id: string): Promise<Result>;
    deleteJournalEntry(id: string): Promise<Result>;
    getBalance(exercice: bigint): Promise<Array<AccountBalance>>;
    getBilan(exercice: bigint): Promise<BilanData>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCompanyInfo(): Promise<CompanyInfo | null>;
    getCompteResultats(exercice: bigint): Promise<CompteResultatsData>;
    getComptes(): Promise<Array<Account>>;
    getComptesParClasse(classe: bigint): Promise<Array<Account>>;
    getComptesTresorerie(): Promise<Array<CompteTresorerie>>;
    getDashboardStats(exercice: bigint): Promise<{
        totalDettes: Amount;
        resultatNet: Amount;
        totalCreances: Amount;
        nombreFacturesEnAttente: bigint;
        alertesStock: bigint;
        chiffreAffaires: Amount;
        soldeTresorerie: Amount;
    }>;
    getExercices(): Promise<Array<FiscalYear>>;
    getFacture(id: string): Promise<Facture | null>;
    getFactures(type: FactureType, exercice: bigint, page: bigint): Promise<{
        total: bigint;
        factures: Array<Facture>;
    }>;
    getGrandLivre(compteNumero: string, exercice: bigint): Promise<Array<JournalEntry>>;
    getJournalEntries(exercice: bigint, page: bigint): Promise<{
        total: bigint;
        entries: Array<JournalEntry>;
    }>;
    getJournalEntry(id: string): Promise<JournalEntry | null>;
    getMouvementsStock(produitId: string | null, exercice: bigint, page: bigint): Promise<{
        mouvements: Array<MouvementStock>;
        total: bigint;
    }>;
    getMouvementsTresorerie(compteId: string | null, exercice: bigint, page: bigint): Promise<{
        mouvements: Array<MouvementTresorerie>;
        total: bigint;
    }>;
    getProduit(id: string): Promise<Produit | null>;
    getProduits(): Promise<Array<Produit>>;
    getProduitsEnRuptureOuAlerte(): Promise<Array<Produit>>;
    getSoldeTresorerie(): Promise<Amount>;
    getTiers(): Promise<Array<Tiers>>;
    getTiersById(id: string): Promise<Tiers | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUsers(): Promise<Array<UserProfile>>;
    getValeurStock(): Promise<Array<ValeurStock>>;
    initData(): Promise<void>;
    initTresorerie(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateCompanyInfo(info: CompanyInfo): Promise<Result>;
    updateCompte(id: string, compte: Account): Promise<Result>;
    updateProduit(id: string, produit: ProduitInput): Promise<Result>;
    updateTiers(id: string, input: TiersInput): Promise<Result>;
    updateUserRole(userId: UserId, role: Role): Promise<Result>;
    validateFacture(id: string): Promise<Result>;
    validateJournalEntry(id: string): Promise<Result>;
}
import type { Account as _Account, AccountBalance as _AccountBalance, AccountType as _AccountType, Amount as _Amount, BilanData as _BilanData, CompanyInfo as _CompanyInfo, CompteResultatsData as _CompteResultatsData, CompteTresorerie as _CompteTresorerie, CompteTresorerieInput as _CompteTresorerieInput, Facture as _Facture, FactureInput as _FactureInput, FactureStatut as _FactureStatut, FactureType as _FactureType, JournalEntry as _JournalEntry, LigneFacture as _LigneFacture, MouvementStock as _MouvementStock, MouvementStockInput as _MouvementStockInput, MouvementTresorerie as _MouvementTresorerie, MouvementTresorerieInput as _MouvementTresorerieInput, MouvementType as _MouvementType, MvtType as _MvtType, Produit as _Produit, Result as _Result, ResultValue as _ResultValue, Role as _Role, Tiers as _Tiers, Timestamp as _Timestamp, TresoType as _TresoType, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCompte(arg0: Account): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.addCompte(to_candid_Account_n8(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCompte(to_candid_Account_n8(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n14(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cloturerExercice(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.cloturerExercice(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cloturerExercice(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCompteTresorerie(arg0: CompteTresorerieInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createCompteTresorerie(to_candid_CompteTresorerieInput_n16(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCompteTresorerie(to_candid_CompteTresorerieInput_n16(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createExercice(arg0: bigint): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createExercice(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createExercice(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createFacture(arg0: FactureInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createFacture(to_candid_FactureInput_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFacture(to_candid_FactureInput_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createJournalEntry(arg0: JournalEntryInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(arg0);
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(arg0);
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMouvementStock(arg0: MouvementStockInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createMouvementStock(to_candid_MouvementStockInput_n29(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMouvementStock(to_candid_MouvementStockInput_n29(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createMouvementTresorerie(arg0: MouvementTresorerieInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createMouvementTresorerie(to_candid_MouvementTresorerieInput_n33(this._uploadFile, this._downloadFile, arg0));
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMouvementTresorerie(to_candid_MouvementTresorerieInput_n33(this._uploadFile, this._downloadFile, arg0));
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduit(arg0: ProduitInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduit(arg0);
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduit(arg0);
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async createTiers(arg0: TiersInput): Promise<ResultValue> {
        if (this.processError) {
            try {
                const result = await this.actor.createTiers(arg0);
                return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTiers(arg0);
            return from_candid_ResultValue_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteFacture(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFacture(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFacture(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteJournalEntry(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBalance(arg0: bigint): Promise<Array<AccountBalance>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBalance(arg0);
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBalance(arg0);
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBilan(arg0: bigint): Promise<BilanData> {
        if (this.processError) {
            try {
                const result = await this.actor.getBilan(arg0);
                return from_candid_BilanData_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBilan(arg0);
            return from_candid_BilanData_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompanyInfo(): Promise<CompanyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanyInfo();
                return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanyInfo();
            return from_candid_opt_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCompteResultats(arg0: bigint): Promise<CompteResultatsData> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompteResultats(arg0);
                return from_candid_CompteResultatsData_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompteResultats(arg0);
            return from_candid_CompteResultatsData_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComptes(): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComptes();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComptes();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComptesParClasse(arg0: bigint): Promise<Array<Account>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComptesParClasse(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComptesParClasse(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getComptesTresorerie(): Promise<Array<CompteTresorerie>> {
        if (this.processError) {
            try {
                const result = await this.actor.getComptesTresorerie();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getComptesTresorerie();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(arg0: bigint): Promise<{
        totalDettes: Amount;
        resultatNet: Amount;
        totalCreances: Amount;
        nombreFacturesEnAttente: bigint;
        alertesStock: bigint;
        chiffreAffaires: Amount;
        soldeTresorerie: Amount;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats(arg0);
            return result;
        }
    }
    async getExercices(): Promise<Array<FiscalYear>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExercices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExercices();
            return result;
        }
    }
    async getFacture(arg0: string): Promise<Facture | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getFacture(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFacture(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFactures(arg0: FactureType, arg1: bigint, arg2: bigint): Promise<{
        total: bigint;
        factures: Array<Facture>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getFactures(to_candid_FactureType_n24(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_record_n74(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFactures(to_candid_FactureType_n24(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_record_n74(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGrandLivre(arg0: string, arg1: bigint): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGrandLivre(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGrandLivre(arg0, arg1);
            return result;
        }
    }
    async getJournalEntries(arg0: bigint, arg1: bigint): Promise<{
        total: bigint;
        entries: Array<JournalEntry>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries(arg0, arg1);
            return result;
        }
    }
    async getJournalEntry(arg0: string): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntry(arg0);
                return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntry(arg0);
            return from_candid_opt_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMouvementsStock(arg0: string | null, arg1: bigint, arg2: bigint): Promise<{
        mouvements: Array<MouvementStock>;
        total: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMouvementsStock(to_candid_opt_n77(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_record_n78(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMouvementsStock(to_candid_opt_n77(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_record_n78(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMouvementsTresorerie(arg0: string | null, arg1: bigint, arg2: bigint): Promise<{
        mouvements: Array<MouvementTresorerie>;
        total: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMouvementsTresorerie(to_candid_opt_n77(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_record_n84(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMouvementsTresorerie(to_candid_opt_n77(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_record_n84(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduit(arg0: string): Promise<Produit | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduit(arg0);
                return from_candid_opt_n90(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduit(arg0);
            return from_candid_opt_n90(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduits(): Promise<Array<Produit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduits();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduits();
            return result;
        }
    }
    async getProduitsEnRuptureOuAlerte(): Promise<Array<Produit>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduitsEnRuptureOuAlerte();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduitsEnRuptureOuAlerte();
            return result;
        }
    }
    async getSoldeTresorerie(): Promise<Amount> {
        if (this.processError) {
            try {
                const result = await this.actor.getSoldeTresorerie();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSoldeTresorerie();
            return result;
        }
    }
    async getTiers(): Promise<Array<Tiers>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTiers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTiers();
            return result;
        }
    }
    async getTiersById(arg0: string): Promise<Tiers | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTiersById(arg0);
                return from_candid_opt_n91(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTiersById(arg0);
            return from_candid_opt_n91(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUsers();
                return from_candid_vec_n92(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUsers();
            return from_candid_vec_n92(this._uploadFile, this._downloadFile, result);
        }
    }
    async getValeurStock(): Promise<Array<ValeurStock>> {
        if (this.processError) {
            try {
                const result = await this.actor.getValeurStock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getValeurStock();
            return result;
        }
    }
    async initData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initData();
            return result;
        }
    }
    async initTresorerie(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initTresorerie();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initTresorerie();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n93(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n93(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCompanyInfo(arg0: CompanyInfo): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanyInfo(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanyInfo(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCompte(arg0: string, arg1: Account): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompte(arg0, to_candid_Account_n8(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompte(arg0, to_candid_Account_n8(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduit(arg0: string, arg1: ProduitInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduit(arg0, arg1);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduit(arg0, arg1);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateTiers(arg0: string, arg1: TiersInput): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTiers(arg0, arg1);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTiers(arg0, arg1);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUserRole(arg0: UserId, arg1: Role): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserRole(arg0, to_candid_Role_n95(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserRole(arg0, to_candid_Role_n95(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateFacture(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.validateFacture(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateFacture(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateJournalEntry(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.validateJournalEntry(arg0);
                return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateJournalEntry(arg0);
            return from_candid_Result_n12(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AccountBalance_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountBalance): AccountBalance {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_AccountType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AccountType): AccountType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Account_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Account): Account {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_BilanData_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BilanData): BilanData {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_CompteResultatsData_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompteResultatsData): CompteResultatsData {
    return from_candid_record_n56(_uploadFile, _downloadFile, value);
}
function from_candid_CompteTresorerie_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompteTresorerie): CompteTresorerie {
    return from_candid_record_n60(_uploadFile, _downloadFile, value);
}
function from_candid_FactureStatut_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FactureStatut): FactureStatut {
    return from_candid_variant_n67(_uploadFile, _downloadFile, value);
}
function from_candid_FactureType_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FactureType): FactureType {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
function from_candid_Facture_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Facture): Facture {
    return from_candid_record_n65(_uploadFile, _downloadFile, value);
}
function from_candid_LigneFacture_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LigneFacture): LigneFacture {
    return from_candid_record_n73(_uploadFile, _downloadFile, value);
}
function from_candid_MouvementStock_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MouvementStock): MouvementStock {
    return from_candid_record_n81(_uploadFile, _downloadFile, value);
}
function from_candid_MouvementTresorerie_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MouvementTresorerie): MouvementTresorerie {
    return from_candid_record_n87(_uploadFile, _downloadFile, value);
}
function from_candid_MouvementType_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MouvementType): MouvementType {
    return from_candid_variant_n83(_uploadFile, _downloadFile, value);
}
function from_candid_MvtType_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MvtType): MvtType {
    return from_candid_variant_n89(_uploadFile, _downloadFile, value);
}
function from_candid_ResultValue_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResultValue): ResultValue {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_TresoType_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TresoType): TresoType {
    return from_candid_variant_n62(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyInfo]): CompanyInfo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Facture]): Facture | null {
    return value.length === 0 ? null : from_candid_Facture_n64(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JournalEntry]): JournalEntry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Produit]): Produit | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Tiers]): Tiers | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalCredit: _Amount;
    estDebiteur: boolean;
    solde: _Amount;
    compte: _Account;
    totalDebit: _Amount;
}): {
    totalCredit: Amount;
    estDebiteur: boolean;
    solde: Amount;
    compte: Account;
    totalDebit: Amount;
} {
    return {
        totalCredit: value.totalCredit,
        estDebiteur: value.estDebiteur,
        solde: value.solde,
        compte: from_candid_Account_n40(_uploadFile, _downloadFile, value.compte),
        totalDebit: value.totalDebit
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    soldeDebit: _Amount;
    classe: bigint;
    libelle: string;
    type: _AccountType;
    numero: string;
    soldeCredit: _Amount;
    compteParent: [] | [string];
}): {
    id: string;
    soldeDebit: Amount;
    classe: bigint;
    libelle: string;
    type: AccountType;
    numero: string;
    soldeCredit: Amount;
    compteParent?: string;
} {
    return {
        id: value.id,
        soldeDebit: value.soldeDebit,
        classe: value.classe,
        libelle: value.libelle,
        type: from_candid_AccountType_n42(_uploadFile, _downloadFile, value.type),
        numero: value.numero,
        soldeCredit: value.soldeCredit,
        compteParent: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.compteParent))
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalActif: _Amount;
    exercice: bigint;
    passifDetails: Array<_AccountBalance>;
    estEquilibre: boolean;
    actifDetails: Array<_AccountBalance>;
    totalPassif: _Amount;
}): {
    totalActif: Amount;
    exercice: bigint;
    passifDetails: Array<AccountBalance>;
    estEquilibre: boolean;
    actifDetails: Array<AccountBalance>;
    totalPassif: Amount;
} {
    return {
        totalActif: value.totalActif,
        exercice: value.exercice,
        passifDetails: from_candid_vec_n37(_uploadFile, _downloadFile, value.passifDetails),
        estEquilibre: value.estEquilibre,
        actifDetails: from_candid_vec_n37(_uploadFile, _downloadFile, value.actifDetails),
        totalPassif: value.totalPassif
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nom: string;
    actif: boolean;
    userId: _UserId;
    role: _Role;
    email: string;
}): {
    nom: string;
    actif: boolean;
    userId: UserId;
    role: Role;
    email: string;
} {
    return {
        nom: value.nom,
        actif: value.actif,
        userId: value.userId,
        role: from_candid_Role_n50(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalProduits: _Amount;
    resultatNet: _Amount;
    produitsDetails: Array<_AccountBalance>;
    exercice: bigint;
    estBenefice: boolean;
    totalCharges: _Amount;
    chargesDetails: Array<_AccountBalance>;
}): {
    totalProduits: Amount;
    resultatNet: Amount;
    produitsDetails: Array<AccountBalance>;
    exercice: bigint;
    estBenefice: boolean;
    totalCharges: Amount;
    chargesDetails: Array<AccountBalance>;
} {
    return {
        totalProduits: value.totalProduits,
        resultatNet: value.resultatNet,
        produitsDetails: from_candid_vec_n37(_uploadFile, _downloadFile, value.produitsDetails),
        exercice: value.exercice,
        estBenefice: value.estBenefice,
        totalCharges: value.totalCharges,
        chargesDetails: from_candid_vec_n37(_uploadFile, _downloadFile, value.chargesDetails)
    };
}
function from_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    actif: boolean;
    libelle: string;
    compteComptable: string;
    type: _TresoType;
    banque: [] | [string];
    solde: _Amount;
    numeroCompte: [] | [string];
}): {
    id: string;
    actif: boolean;
    libelle: string;
    compteComptable: string;
    type: TresoType;
    banque?: string;
    solde: Amount;
    numeroCompte?: string;
} {
    return {
        id: value.id,
        actif: value.actif,
        libelle: value.libelle,
        compteComptable: value.compteComptable,
        type: from_candid_TresoType_n61(_uploadFile, _downloadFile, value.type),
        banque: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.banque)),
        solde: value.solde,
        numeroCompte: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.numeroCompte))
    };
}
function from_candid_record_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    statut: _FactureStatut;
    date: _Timestamp;
    totalHT: _Amount;
    tiersId: string;
    type: _FactureType;
    exercice: bigint;
    dateEcheance: [] | [_Timestamp];
    totalTTC: _Amount;
    totalTVA: _Amount;
    notes: string;
    numero: string;
    lignes: Array<_LigneFacture>;
}): {
    id: string;
    statut: FactureStatut;
    date: Timestamp;
    totalHT: Amount;
    tiersId: string;
    type: FactureType;
    exercice: bigint;
    dateEcheance?: Timestamp;
    totalTTC: Amount;
    totalTVA: Amount;
    notes: string;
    numero: string;
    lignes: Array<LigneFacture>;
} {
    return {
        id: value.id,
        statut: from_candid_FactureStatut_n66(_uploadFile, _downloadFile, value.statut),
        date: value.date,
        totalHT: value.totalHT,
        tiersId: value.tiersId,
        type: from_candid_FactureType_n68(_uploadFile, _downloadFile, value.type),
        exercice: value.exercice,
        dateEcheance: record_opt_to_undefined(from_candid_opt_n70(_uploadFile, _downloadFile, value.dateEcheance)),
        totalTTC: value.totalTTC,
        totalTVA: value.totalTVA,
        notes: value.notes,
        numero: value.numero,
        lignes: from_candid_vec_n71(_uploadFile, _downloadFile, value.lignes)
    };
}
function from_candid_record_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    montantHT: _Amount;
    montantTTC: _Amount;
    montantTVA: _Amount;
    designation: string;
    tauxTVA: number;
    produitId: [] | [string];
    quantite: number;
    prixUnitaire: _Amount;
}): {
    montantHT: Amount;
    montantTTC: Amount;
    montantTVA: Amount;
    designation: string;
    tauxTVA: number;
    produitId?: string;
    quantite: number;
    prixUnitaire: Amount;
} {
    return {
        montantHT: value.montantHT,
        montantTTC: value.montantTTC,
        montantTVA: value.montantTVA,
        designation: value.designation,
        tauxTVA: value.tauxTVA,
        produitId: record_opt_to_undefined(from_candid_opt_n44(_uploadFile, _downloadFile, value.produitId)),
        quantite: value.quantite,
        prixUnitaire: value.prixUnitaire
    };
}
function from_candid_record_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    total: bigint;
    factures: Array<_Facture>;
}): {
    total: bigint;
    factures: Array<Facture>;
} {
    return {
        total: value.total,
        factures: from_candid_vec_n75(_uploadFile, _downloadFile, value.factures)
    };
}
function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mouvements: Array<_MouvementStock>;
    total: bigint;
}): {
    mouvements: Array<MouvementStock>;
    total: bigint;
} {
    return {
        mouvements: from_candid_vec_n79(_uploadFile, _downloadFile, value.mouvements),
        total: value.total
    };
}
function from_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    date: _Timestamp;
    type: _MouvementType;
    exercice: bigint;
    reference: string;
    produitId: string;
    notes: string;
    quantite: number;
    prixUnitaire: _Amount;
}): {
    id: string;
    date: Timestamp;
    type: MouvementType;
    exercice: bigint;
    reference: string;
    produitId: string;
    notes: string;
    quantite: number;
    prixUnitaire: Amount;
} {
    return {
        id: value.id,
        date: value.date,
        type: from_candid_MouvementType_n82(_uploadFile, _downloadFile, value.type),
        exercice: value.exercice,
        reference: value.reference,
        produitId: value.produitId,
        notes: value.notes,
        quantite: value.quantite,
        prixUnitaire: value.prixUnitaire
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mouvements: Array<_MouvementTresorerie>;
    total: bigint;
}): {
    mouvements: Array<MouvementTresorerie>;
    total: bigint;
} {
    return {
        mouvements: from_candid_vec_n85(_uploadFile, _downloadFile, value.mouvements),
        total: value.total
    };
}
function from_candid_record_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    libelle: string;
    date: _Timestamp;
    type: _MvtType;
    exercice: bigint;
    reference: string;
    compteId: string;
    montant: _Amount;
}): {
    id: string;
    libelle: string;
    date: Timestamp;
    type: MvtType;
    exercice: bigint;
    reference: string;
    compteId: string;
    montant: Amount;
} {
    return {
        id: value.id,
        libelle: value.libelle,
        date: value.date,
        type: from_candid_MvtType_n88(_uploadFile, _downloadFile, value.type),
        exercice: value.exercice,
        reference: value.reference,
        compteId: value.compteId,
        montant: value.montant
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Passif: null;
} | {
    Bilan: null;
} | {
    Charges: null;
} | {
    Produits: null;
} | {
    Actif: null;
}): AccountType {
    return "Passif" in value ? AccountType.Passif : "Bilan" in value ? AccountType.Bilan : "Charges" in value ? AccountType.Charges : "Produits" in value ? AccountType.Produits : "Actif" in value ? AccountType.Actif : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Lecteur: null;
} | {
    Gestionnaire: null;
} | {
    Comptable: null;
} | {
    Admin: null;
}): Role {
    return "Lecteur" in value ? Role.Lecteur : "Gestionnaire" in value ? Role.Gestionnaire : "Comptable" in value ? Role.Comptable : "Admin" in value ? Role.Admin : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Banque: null;
} | {
    Caisse: null;
}): TresoType {
    return "Banque" in value ? TresoType.Banque : "Caisse" in value ? TresoType.Caisse : value;
}
function from_candid_variant_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Annulee: null;
} | {
    Validee: null;
} | {
    Payee: null;
} | {
    Brouillon: null;
}): FactureStatut {
    return "Annulee" in value ? FactureStatut.Annulee : "Validee" in value ? FactureStatut.Validee : "Payee" in value ? FactureStatut.Payee : "Brouillon" in value ? FactureStatut.Brouillon : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Achat: null;
} | {
    Vente: null;
}): FactureType {
    return "Achat" in value ? FactureType.Achat : "Vente" in value ? FactureType.Vente : value;
}
function from_candid_variant_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Entree: null;
} | {
    Sortie: null;
} | {
    Ajustement: null;
}): MouvementType {
    return "Entree" in value ? MouvementType.Entree : "Sortie" in value ? MouvementType.Sortie : "Ajustement" in value ? MouvementType.Ajustement : value;
}
function from_candid_variant_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Decaissement: null;
} | {
    Encaissement: null;
}): MvtType {
    return "Decaissement" in value ? MvtType.Decaissement : "Encaissement" in value ? MvtType.Encaissement : value;
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AccountBalance>): Array<AccountBalance> {
    return value.map((x)=>from_candid_AccountBalance_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Account>): Array<Account> {
    return value.map((x)=>from_candid_Account_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CompteTresorerie>): Array<CompteTresorerie> {
    return value.map((x)=>from_candid_CompteTresorerie_n59(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LigneFacture>): Array<LigneFacture> {
    return value.map((x)=>from_candid_LigneFacture_n72(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Facture>): Array<Facture> {
    return value.map((x)=>from_candid_Facture_n64(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MouvementStock>): Array<MouvementStock> {
    return value.map((x)=>from_candid_MouvementStock_n80(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MouvementTresorerie>): Array<MouvementTresorerie> {
    return value.map((x)=>from_candid_MouvementTresorerie_n86(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n48(_uploadFile, _downloadFile, x));
}
function to_candid_AccountType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): _AccountType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Account_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Account): _Account {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_CompteTresorerieInput_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompteTresorerieInput): _CompteTresorerieInput {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_FactureInput_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FactureInput): _FactureInput {
    return to_candid_record_n23(_uploadFile, _downloadFile, value);
}
function to_candid_FactureType_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FactureType): _FactureType {
    return to_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function to_candid_LigneFacture_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LigneFacture): _LigneFacture {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_MouvementStockInput_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MouvementStockInput): _MouvementStockInput {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_MouvementTresorerieInput_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MouvementTresorerieInput): _MouvementTresorerieInput {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_MouvementType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MouvementType): _MouvementType {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_MvtType_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MvtType): _MvtType {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n96(_uploadFile, _downloadFile, value);
}
function to_candid_TresoType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TresoType): _TresoType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n94(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    libelle: string;
    compteComptable: string;
    soldeinitial: Amount;
    type: TresoType;
    banque?: string;
    numeroCompte?: string;
}): {
    libelle: string;
    compteComptable: string;
    soldeinitial: _Amount;
    type: _TresoType;
    banque: [] | [string];
    numeroCompte: [] | [string];
} {
    return {
        libelle: value.libelle,
        compteComptable: value.compteComptable,
        soldeinitial: value.soldeinitial,
        type: to_candid_TresoType_n18(_uploadFile, _downloadFile, value.type),
        banque: value.banque ? candid_some(value.banque) : candid_none(),
        numeroCompte: value.numeroCompte ? candid_some(value.numeroCompte) : candid_none()
    };
}
function to_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Timestamp;
    tiersId: string;
    type: FactureType;
    exercice: bigint;
    dateEcheance?: Timestamp;
    notes: string;
    lignes: Array<LigneFacture>;
}): {
    date: _Timestamp;
    tiersId: string;
    type: _FactureType;
    exercice: bigint;
    dateEcheance: [] | [_Timestamp];
    notes: string;
    lignes: Array<_LigneFacture>;
} {
    return {
        date: value.date,
        tiersId: value.tiersId,
        type: to_candid_FactureType_n24(_uploadFile, _downloadFile, value.type),
        exercice: value.exercice,
        dateEcheance: value.dateEcheance ? candid_some(value.dateEcheance) : candid_none(),
        notes: value.notes,
        lignes: to_candid_vec_n26(_uploadFile, _downloadFile, value.lignes)
    };
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    montantHT: Amount;
    montantTTC: Amount;
    montantTVA: Amount;
    designation: string;
    tauxTVA: number;
    produitId?: string;
    quantite: number;
    prixUnitaire: Amount;
}): {
    montantHT: _Amount;
    montantTTC: _Amount;
    montantTVA: _Amount;
    designation: string;
    tauxTVA: number;
    produitId: [] | [string];
    quantite: number;
    prixUnitaire: _Amount;
} {
    return {
        montantHT: value.montantHT,
        montantTTC: value.montantTTC,
        montantTVA: value.montantTVA,
        designation: value.designation,
        tauxTVA: value.tauxTVA,
        produitId: value.produitId ? candid_some(value.produitId) : candid_none(),
        quantite: value.quantite,
        prixUnitaire: value.prixUnitaire
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: Timestamp;
    type: MouvementType;
    exercice: bigint;
    reference: string;
    produitId: string;
    notes: string;
    quantite: number;
    prixUnitaire: Amount;
}): {
    date: _Timestamp;
    type: _MouvementType;
    exercice: bigint;
    reference: string;
    produitId: string;
    notes: string;
    quantite: number;
    prixUnitaire: _Amount;
} {
    return {
        date: value.date,
        type: to_candid_MouvementType_n31(_uploadFile, _downloadFile, value.type),
        exercice: value.exercice,
        reference: value.reference,
        produitId: value.produitId,
        notes: value.notes,
        quantite: value.quantite,
        prixUnitaire: value.prixUnitaire
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    libelle: string;
    date: Timestamp;
    type: MvtType;
    exercice: bigint;
    reference: string;
    compteId: string;
    montant: Amount;
}): {
    libelle: string;
    date: _Timestamp;
    type: _MvtType;
    exercice: bigint;
    reference: string;
    compteId: string;
    montant: _Amount;
} {
    return {
        libelle: value.libelle,
        date: value.date,
        type: to_candid_MvtType_n35(_uploadFile, _downloadFile, value.type),
        exercice: value.exercice,
        reference: value.reference,
        compteId: value.compteId,
        montant: value.montant
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    soldeDebit: Amount;
    classe: bigint;
    libelle: string;
    type: AccountType;
    numero: string;
    soldeCredit: Amount;
    compteParent?: string;
}): {
    id: string;
    soldeDebit: _Amount;
    classe: bigint;
    libelle: string;
    type: _AccountType;
    numero: string;
    soldeCredit: _Amount;
    compteParent: [] | [string];
} {
    return {
        id: value.id,
        soldeDebit: value.soldeDebit,
        classe: value.classe,
        libelle: value.libelle,
        type: to_candid_AccountType_n10(_uploadFile, _downloadFile, value.type),
        numero: value.numero,
        soldeCredit: value.soldeCredit,
        compteParent: value.compteParent ? candid_some(value.compteParent) : candid_none()
    };
}
function to_candid_record_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    nom: string;
    actif: boolean;
    userId: UserId;
    role: Role;
    email: string;
}): {
    nom: string;
    actif: boolean;
    userId: _UserId;
    role: _Role;
    email: string;
} {
    return {
        nom: value.nom,
        actif: value.actif,
        userId: value.userId,
        role: to_candid_Role_n95(_uploadFile, _downloadFile, value.role),
        email: value.email
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AccountType): {
    Passif: null;
} | {
    Bilan: null;
} | {
    Charges: null;
} | {
    Produits: null;
} | {
    Actif: null;
} {
    return value == AccountType.Passif ? {
        Passif: null
    } : value == AccountType.Bilan ? {
        Bilan: null
    } : value == AccountType.Charges ? {
        Charges: null
    } : value == AccountType.Produits ? {
        Produits: null
    } : value == AccountType.Actif ? {
        Actif: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TresoType): {
    Banque: null;
} | {
    Caisse: null;
} {
    return value == TresoType.Banque ? {
        Banque: null
    } : value == TresoType.Caisse ? {
        Caisse: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FactureType): {
    Achat: null;
} | {
    Vente: null;
} {
    return value == FactureType.Achat ? {
        Achat: null
    } : value == FactureType.Vente ? {
        Vente: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MouvementType): {
    Entree: null;
} | {
    Sortie: null;
} | {
    Ajustement: null;
} {
    return value == MouvementType.Entree ? {
        Entree: null
    } : value == MouvementType.Sortie ? {
        Sortie: null
    } : value == MouvementType.Ajustement ? {
        Ajustement: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MvtType): {
    Decaissement: null;
} | {
    Encaissement: null;
} {
    return value == MvtType.Decaissement ? {
        Decaissement: null
    } : value == MvtType.Encaissement ? {
        Encaissement: null
    } : value;
}
function to_candid_variant_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    Lecteur: null;
} | {
    Gestionnaire: null;
} | {
    Comptable: null;
} | {
    Admin: null;
} {
    return value == Role.Lecteur ? {
        Lecteur: null
    } : value == Role.Gestionnaire ? {
        Gestionnaire: null
    } : value == Role.Comptable ? {
        Comptable: null
    } : value == Role.Admin ? {
        Admin: null
    } : value;
}
function to_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LigneFacture>): Array<_LigneFacture> {
    return value.map((x)=>to_candid_LigneFacture_n27(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
